interface Format {
    asr: number | null;
    filesize: number | null;
    filesizeP: string;
    format_note: string;
    tbr: number | null;
    url: string;
    ext: string;
    acodec: string | null;
    container: string;
    resolution: string;
    audio_ext: string | null;
    abr: number | null;
    format: string;
    format_id: string;
    source_preference: number | null;
    fps: number | null;
    audio_channels: number | null;
    height: number | null;
    quality: number | null;
    has_drm: boolean | null;
    filesize_approx: number | null;
    width: number | null;
    language: string | null;
    preference: number | null;
    vbr: number | null;
    vcodec: string | null;
    protocol: string | null;
    video_ext: string | null;
    aspect_ratio: number | null;
    manifest_url: string | null;
    dynamic_range: string | null;
    language_preference: number | null;
    downloader_options: { http_chunk_size: number } | null;
    http_headers: { "User-Agent": string; Accept: string; "Accept-Language": string; "Sec-Fetch-Mode": string } | null;
}
interface Comment {
    comment_id: string;
    is_pinned: boolean;
    comment: string;
    published_time: string;
    author_is_channel_owner: boolean;
    creator_thumbnail_url: string;
    like_count: string;
    is_member: boolean;
    author: string;
    is_hearted: boolean;
    is_liked: boolean;
    is_disliked: boolean;
    reply_count: string;
    hasReplies: boolean;
}
interface MetaData {
    id: string;
    title: string;
    channel: string;
    uploader: string;
    duration: number;
    thumbnail: string;
    age_limit: number;
    channel_id: string;
    categories: string[];
    display_id: string;
    view_count: number;
    like_count: number;
    description: string | null;
    channel_url: string;
    webpage_url: string;
    live_status: string;
    upload_date: string;
    uploader_id: string;
    original_url: string;
    uploader_url: string;
    comment_count: number;
    duration_string: string;
    channel_follower_count: number;
    view_count_formatted: string;
    like_count_formatted: string;
    upload_ago: number;
    upload_ago_formatted: { years: number; months: number; days: number; formatted: string };
    comment_count_formatted: string;
    channel_follower_count_formatted: string;
}
interface ExtractedVideoData {
    data: {
        BestAudioLow: Format;
        BestAudioHigh: Format;
        BestVideoLow: Format;
        BestVideoHigh: Format;
        AudioLowDRC: Format[];
        AudioHighDRC: Format[];
        AudioLow: Format[];
        AudioHigh: Format[];
        VideoLowHDR: Format[];
        VideoHighHDR: Format[];
        VideoLow: Format[];
        VideoHigh: Format[];
        ManifestLow: Format[];
        ManifestHigh: Format[];
        meta_data: MetaData;
        comments: Comment[];
        transcript: any;
    };
}
