import M3U8Downloader from "@renmu/m3u8-downloader";
import { locator } from "../utils/Locator";
import progbar from "../utils/ProgBar";
import Ffmpeg from "fluent-ffmpeg";
import dotenv from "dotenv";
import YouTubeDLX from "..";
import fs from "fs";
dotenv.config();
console.clear();
(async () => {
    const respEngine = await YouTubeDLX.Misc.Video.Extract({ Query: "dil ibadat" });
    fs.writeFileSync("Engine.json", JSON.stringify(respEngine, null, 2));
    const paths = await locator();
    const FileName = respEngine.MetaData.title?.toString()! + "mkv";
    const AudName = `${Math.floor(Math.random() * 10000)}_${respEngine.MetaData.last_fetched?.toString()!}.mp4`;
    const AudDev = new Promise<void>((resolve, reject) => {
        const main = new M3U8Downloader(respEngine.AudioOnly.Standard["Default,"].Highest?.url!, AudName, { ffmpegPath: paths.ffmpeg, convert2Mp4: true });
        main.on("progress", progress => process.stdout.write(`${progress}\r`));
        main.on("error", error => reject(error));
        main.on("completed", () => resolve());
        main.download();
    });
    await AudDev;
    let processStartTime: Date;
    const instance: Ffmpeg.FfmpegCommand = Ffmpeg();
    instance.addInput(AudName);
    instance.setFfmpegPath(paths.ffmpeg);
    instance.setFfprobePath(paths.ffprobe);
    instance.addInput(respEngine.VideoOnly.Standard_Dynamic_Range.Highest?.url!);
    instance.addInputOption("-protocol_whitelist", "file,http,https,tcp,tls,crypto");
    instance.withOutputFormat("matroska");
    instance.outputOptions("-c copy");
    instance.on("end", () => fs.unlinkSync(AudName));
    instance.on("start", () => (processStartTime = new Date()));
    instance.on("progress", progress => progbar({ ...progress, percent: progress.percent ?? 0, startTime: processStartTime }));
    instance.output(FileName);
    instance.run();
})().catch(console.error);
