export interface OriginalJson {
    id?: string;
    title?: string;
    formats?: {
        format_id?: string;
        format_note?: string | null;
        format_index?: number | null;
        url?: string;
        manifest_url?: string;
        language?: string | null;
        ext?: string;
        protocol?: string;
        preference?: number | null;
        quality?: number | string | null;
        has_drm?: boolean;
        vcodec?: string | null;
        acodec?: string | null;
        source_preference?: number;
        __needs_testing?: boolean;
        audio_ext?: string;
        video_ext?: string;
        vbr?: number | null;
        abr?: number | null;
        tbr?: number | null;
        resolution?: string | null;
        aspect_ratio?: number | null;
        filesize_approx?: number | null;
        http_headers?: { "User-Agent"?: string; Accept?: string; "Accept-Language"?: string; "Sec-Fetch-Mode"?: string };
        format?: string;
        width?: number | null;
        height?: number | null;
        fps?: number | null;
        rows?: number;
        columns?: number;
        fragments?: { url?: string; duration?: number }[];
        dynamic_range?: string;
        __working?: boolean;
        stretched_ratio?: number | null;
        asr?: number | null;
        audio_channels?: number | null;
    }[];
    thumbnails?: { url?: string; preference?: number; id?: string; height?: number; width?: number; resolution?: string }[];
    thumbnail?: string;
    description?: string;
    channel_id?: string;
    channel_url?: string;
    duration?: number;
    view_count?: number;
    average_rating?: number | null;
    age_limit?: number;
    webpage_url?: string;
    categories?: string[];
    tags?: string[];
    playable_in_embed?: boolean;
    live_status?: string;
    media_type?: string | null;
    release_timestamp?: number | null;
    _format_sort_fields?: string[];
    automatic_captions?: { [languageCode: string]: { ext: string; url: string; name: string }[] };
    subtitles?: { [languageCode: string]: { ext: string; url: string; name: string }[] };
    comment_count?: number;
    chapters?: { chapters: { start_time: number; end_time: number; title: string }[] };
    heatmap?: { heatmap: { start_time: number; end_time: number; value: number }[] };
    like_count?: number;
    channel?: string;
    channel_follower_count?: number;
    channel_is_verified?: boolean;
    uploader?: string;
    uploader_id?: string;
    uploader_url?: string;
    upload_date?: string;
    timestamp?: number;
    availability?: string;
    original_url?: string;
    webpage_url_basename?: string;
    webpage_url_domain?: string;
    extractor?: string;
    extractor_key?: string;
    playlist?: null;
    playlist_index?: null;
    display_id?: string;
    fulltitle?: string;
    duration_string?: string;
    release_year?: number | null;
    is_live?: boolean;
    was_live?: boolean;
    requested_subtitles?: null;
    _has_drm?: null;
    epoch?: number;
    requested_formats?: {
        format_id?: string;
        format_index?: number | null;
        url?: string;
        manifest_url?: string;
        language?: string | null;
        ext?: string;
        protocol?: string;
        preference?: number | null;
        quality?: number | string | null;
        has_drm?: boolean;
        vcodec?: string | null;
        source_preference?: number;
        __needs_testing?: boolean;
        audio_ext?: string;
        video_ext?: string;
        vbr?: number | null;
        abr?: number | null;
        tbr?: number | null;
        resolution?: string | null;
        aspect_ratio?: number | null;
        filesize_approx?: number | null;
        http_headers?: { "User-Agent"?: string; Accept?: string; "Accept-Language"?: string; "Sec-Fetch-Mode"?: string };
        format?: string;
        width?: number | null;
        height?: number | null;
        fps?: number | null;
        dynamic_range?: string;
        __working?: boolean;
        stretched_ratio?: number | null;
        asr?: number | null;
        audio_channels?: number | null;
    }[];
    requested_downloads?: {
        requested_formats?: {
            format_id?: string;
            format_index?: number | null;
            url?: string;
            manifest_url?: string;
            language?: string | null;
            ext?: string;
            protocol?: string;
            preference?: number | null;
            quality?: number | string | null;
            has_drm?: boolean;
            vcodec?: string | null;
            source_preference?: number;
            __needs_testing?: boolean;
            audio_ext?: string;
            video_ext?: string;
            vbr?: number | null;
            abr?: number | null;
            tbr?: number | null;
            resolution?: string | null;
            aspect_ratio?: number | null;
            files_approx?: number | null;
            http_headers?: { "User-Agent"?: string; Accept?: string; "Accept-Language"?: string; "Sec-Fetch-Mode"?: string };
            format?: string;
            width?: number;
            height?: number;
            fps?: number | null;
            dynamic_range?: string;
            __working?: boolean;
            stretched_ratio?: number | null;
            asr?: number | null;
            audio_channels?: number | null;
        }[];
        format?: string;
        format_id?: string;
        ext?: string;
        protocol?: string;
        format_note?: string;
        tbr?: number;
        width?: number;
        height?: number;
        resolution?: string;
        fps?: number;
        dynamic_range?: string;
        vcodec?: string | null;
        vbr?: number;
        aspect_ratio?: number;
        _filename?: string;
        filename?: string;
        __write_download_archive?: boolean;
    }[];
    format?: string;
    format_id?: string;
    ext?: string;
    protocol?: string;
    language?: string | null;
    format_note?: string | null;
    filesize_approx?: number | null;
    tbr?: number | null;
    width?: number | null;
    height?: number | null;
    resolution?: string | null;
    fps?: number | null;
    dynamic_range?: string | null;
    vcodec?: string | null;
    vbr?: number | null;
    stretched_ratio?: number | null;
    aspect_ratio?: number | null;
    acodec?: string | null;
    abr?: number | null;
    asr?: number | null;
    audio_channels?: number | null;
    _type?: string;
    _version?: { version?: string; current_git_head?: string | null; release_git_head?: string | null; repository?: string };
}
export interface CleanedAudioFormat extends Omit<NonNullable<OriginalJson["formats"]>[number], "format"> {
    __needs_testing?: never;
    http_headers?: never;
    format_index?: never;
    __working?: never;
    abr?: never;
    format_id?: string;
    format_note?: string | null;
    url?: string;
    manifest_url?: string;
    language?: string | null;
    protocol?: string;
    has_drm?: boolean;
    audio_ext?: string;
    tbr?: number | null;
}
export interface CleanedVideoFormat extends Omit<NonNullable<OriginalJson["formats"]>[number], "format"> {
    __needs_testing?: never;
    http_headers?: never;
    format_index?: never;
    __working?: never;
    format_id?: string;
    url?: string;
    manifest_url?: string;
    tbr?: number | null;
    ext?: string;
    fps?: number | null;
    protocol?: string;
    quality?: number | string | null;
    has_drm?: boolean;
    width?: number | null;
    height?: number | null;
    vcodec?: string | null;
    dynamic_range?: string;
    video_ext?: string;
    vbr?: number | null;
    resolution?: string | null;
    aspect_ratio?: number | null;
}
export interface EngineOutput {
    MetaData: {
        videoId?: string;
        videoLink?: string;
        title?: string;
        description?: string;
        channel_id?: string;
        channel_url?: string;
        duration?: number;
        view_count?: number;
        average_rating?: number | null;
        age_limit?: number;
        categories?: string[];
        playable_in_embed?: boolean;
        live_status?: string;
        media_type?: string | null;
        release_timestamp?: number | null;
        _format_sort_fields?: string[];
        like_count?: number;
        channel?: string;
        channel_follower_count?: number;
        channel_is_verified?: boolean;
        uploader?: string;
        uploader_id?: string;
        uploader_url?: string;
        upload_date?: string;
        timestamp?: number;
        availability?: string;
        original_url?: string;
        webpage_url_basename?: string;
        webpage_url_domain?: string;
        extractor?: string;
        extractor_key?: string;
        playlist?: null;
        playlist_index?: null;
        display_id?: string;
        fulltitle?: string;
        duration_string?: string;
        release_year?: number | null;
        is_live?: boolean;
        was_live?: boolean;
        requested_subtitles?: null;
        _has_drm?: null;
        last_fetched?: number;
        tags?: string[];
    };
    AudioOnly: {
        Standard: { [key: string]: { Highest: CleanedAudioFormat | null; Lowest: CleanedAudioFormat | null; Combined: CleanedAudioFormat[] } };
        Dynamic_Range_Compression: { [key: string]: { Highest: CleanedAudioFormat | null; Lowest: CleanedAudioFormat | null; Combined: CleanedAudioFormat[] } };
    };
    VideoOnly: {
        Standard_Dynamic_Range: { Highest: CleanedVideoFormat | null; Lowest: CleanedVideoFormat | null; Combined: CleanedVideoFormat[] };
        High_Dynamic_Range: { Highest: CleanedVideoFormat | null; Lowest: CleanedVideoFormat | null; Combined: CleanedVideoFormat[] };
    };
    Thumbnails: {
        Highest: NonNullable<OriginalJson["thumbnails"]>[number] | null;
        Lowest: NonNullable<OriginalJson["thumbnails"]>[number] | null;
        Combined: NonNullable<OriginalJson["thumbnails"]>[number][];
    };
    Heatmap: OriginalJson["heatmap"] | [];
    Chapters: OriginalJson["chapters"] | [];
    Subtitle: OriginalJson["subtitles"] | [];
    Captions: OriginalJson["automatic_captions"] | [];
}
